name: Build for Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest ]
        arch: [ x64 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Cache fftw3
      id: cache-fftw3
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/vcpkg/installed/
        key: ${{ runner.os }}-fftw3-v1

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      if: steps.cache-fftw3.outputs.cache-hit != 'true'
      with:
        vcpkgArguments: 'fftw3[avx2,threads]:x64-windows-static'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092 # 2021.05.12 release

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: install meson and ninja
      run: pip install meson ninja

    - name: Plug in vs-api3
      shell: bash
      run: |
        git clone https://github.com/AmusementClub/vs-api3 --depth=1 --branch master api3
        cp api3/api3.cc .
        sed -i -e "/Plugin.cpp'/s//&, 'api3.cc'/" meson.build
        cat meson.build

    - name: download VS headers and patch header location
      shell: bash
      run: |
        git clone https://github.com/AmusementClub/vapoursynth-classic --depth=1 --branch doodle2 vapoursynth
        cp vapoursynth/include/*.h .
        sed -i -e '/#include <V/y|<>|""|' *.cpp *.h

    - name: setup MS dev commands
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Install pkg-config lite
      run: choco install pkgconfiglite --allow-empty-checksums

    - name: Meson setup
      run: meson setup builddir/ -Db_vscrt=mt -Dpkg_config_path=${{ github.workspace }}/vcpkg/installed/x64-windows-static/lib/pkgconfig
      env:
        CXX: clang-cl
        CXXFLAGS: "-mavx -Xclang -ffast-math"

    - name: Meson compile
      run: meson compile -C builddir/ -v

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{matrix.arch}}
        path: |
          builddir/*.dll

    - name: Setup Python portable
      run: |
        curl -s -o python.zip -LJO https://www.python.org/ftp/python/3.11.2/python-3.11.2-embed-amd64.zip
        7z x python.zip -ovs_portable

    - name: Install VapourSynth portable
      run: |
        curl -s -o vs.7z -LJO https://github.com/AmusementClub/vapoursynth-classic/releases/download/R57.A8/release-x64.zip
        7z x vs.7z -ovs_portable -y

    - name: Copy plugin
      run: cp builddir/*.dll vs_portable/vapoursynth64/plugins

    - name: Download sde
      run: curl -o sde.tar.xz -LJO https://downloadmirror.intel.com/751535/sde-external-9.14.0-2022-10-25-win.tar.xz

    - name: Setup sde
      run: |
        7z x sde.tar.xz
        7z x sde.tar
        mv sde-* sde

    - name: Create script
      shell: bash
      run: echo "import vapoursynth as vs;from vapoursynth import core;import sys;print(core.fft3dfilter, file=sys.stderr);core.std.BlankClip(width=128, height=128, format=vs.GRAY16).fft3dfilter.FFT3DFilter().set_output()" > test.vpy

    - name: Run vspipe
      shell: bash
      run: |
        set -ex
        vs_portable/vspipe -i test.vpy .
        vs_portable/vspipe -p -e 9 test.vpy .
        sde/sde.exe -ivb -- vs_portable/vspipe -p -e 9 test.vpy .
